### ISSUE TITLE
Mysterious bug when reading restart file.

### ISSUE THREAD

**Issue by leeping** [rmcgibbo/openmm-cmd#6]
Hi Robert,

I can't figure out why the cPickle.load() function expects four input arguments.  The documentation is turning up nothing.
- Lee-Ping

```
Traceback (most recent call last):
  File "/home/leeping/local/bin/openmm", line 5, in <module>
    pkg_resources.run_script('openmm-cmd==0.1', 'openmm')
  File "/home/leeping/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 489, in run_script
  File "/home/leeping/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 1207, in run_script
  File "/home/leeping/local/lib/python2.7/site-packages/openmm_cmd-0.1-py2.7.egg/EGG-INFO/scripts/openmm", line 964, in <module>
    openmm.start()
  File "/home/leeping/local/lib/python2.7/site-packages/openmm_cmd-0.1-py2.7.egg/EGG-INFO/scripts/openmm", line 773, in start
    loadRestartFile(simulation, self.simulation.restart_file)
  File "/home/leeping/local/lib/python2.7/site-packages/openmm_cmd-0.1-py2.7.egg/ipcfg/restartreporter.py", line 212, in loadRestartFile
    data = pickle.load(f)
TypeError: __new__() takes exactly 4 arguments (2 given)
```

**Comment by leeping** [comment]
Locally I changed to json instead of pickle.  It seems to work well, plus it may have other advantages such as cross-platform compatibility.  Let me know what you think.

**Comment by rmcgibbo** [comment]
I fixed this bug in OpenMM pr #69.  Have you updated?

-Robert

**Comment by leeping** [comment]
Thank you.  I needed to update.  Should we stay with pickle or switch to json?  I'm fine either way.

**Comment by rmcgibbo** [comment]
Can you check the size difference between the two types of files for the same system? I don't see anything wrong with json, but it is ASCII and I think pickle2 is binary.

-Robert

**Comment by leeping** [comment]
It looks like the json-generated file is a bit bigger than the pickle, but just by a little bit.  I may have been influenced by the people on the #python IRC chat channel who consistently dislike pickle for having low cross-platform compatibility, having security vulnerabilities and whatnot.  I don't have a particularly strong preference, but if you think json seems like a decent option, we can try it out.  

```
leeping@leeping:~/temp/openmm-cmd-examples/04-ExamplePDB-Restart$ ls restart* -ltra
-rw-rw-r-- 1 leeping leeping 1111432 2013-08-09 14:30 restart.json
-rw-rw-r-- 1 leeping leeping  762148 2013-08-09 16:32 restart.p
```

**Comment by rmcgibbo** [comment]
we switched to the json config file, so this is no longer an issue anyways.
