### ISSUE TITLE
Bad errors. 

### ISSUE THREAD

**Issue by rmcgibbo** [rmcgibbo/openmm-cmd#9]
```
$ openmm --coords ~/local/openmm/examples/input.pdb                                       

>>> ###################################################################
>>> # To use this script, paste all of the lines starting with the
>>> # three less than signs (>>>) into a python interpreter.
>>> ###################################################################
>>> 
>>> from simtk.unit import *
>>> from simtk import openmm as mm
>>> from simtk.openmm import app
>>> 
>>> pdb = app.PDBFile('/home/rmcgibbo/local/openmm/examples/input.pdb')
>>> topology = pdb.topology
>>> positions = pdb.positions
>>> system = forcefield.createSystem(topology,nonbondedMethod=PME,constraints=HBonds
... ,rigidWater=True,nonbondedCutoff=1.0*nanometer,useDispersionCorrection=True,ewal
... dErrorTolerance=0.0005)
Traceback (most recent call last):
  File "/home/rmcgibbo/envs/latest/bin/openmm", line 1059, in <module>
    openmm.start()
  File "/home/rmcgibbo/envs/latest/bin/openmm", line 842, in start
    system = forcefield.createSystem(topology, **system_options)
UnboundLocalError: local variable 'forcefield' referenced before assignment
```

The logic at the beginning of the start() method is not robust.

**Comment by leeping** [comment]
Hopefully it's fixed now.
